### ISSUE TITLE
broccoli-viz crashes

### ISSUE THREAD

**Issue by jurecuhalev** [stefanpenner/broccoli-viz#45]
After doing:

`BROCCOLI_VIZ=1 SITE=sitename ember build` I get a number of instrumentation files:
https://www.dropbox.com/s/df4zovvqhbyfygj/instrumentation.zip?dl=0

When I run:
`broccoli-viz instrumentation.build.0.json > instrumentation.build.0.dot`

It crashes:
```

/usr/local/Cellar/node@6/6.14.1/lib/node_modules/broccoli-viz/lib/build-graph.js:23
  node.children.forEach(function (id) {
      ^

TypeError: Cannot read property 'children' of undefined
    at visitPostOrder (/usr/local/Cellar/node@6/6.14.1/lib/node_modules/broccoli-viz/lib/build-graph.js:23:7)
    at /usr/local/Cellar/node@6/6.14.1/lib/node_modules/broccoli-viz/lib/build-graph.js:25:5
    at Array.forEach (native)
    at visitPostOrder (/usr/local/Cellar/node@6/6.14.1/lib/node_modules/broccoli-viz/lib/build-graph.js:23:17)
    at annotateNodes (/usr/local/Cellar/node@6/6.14.1/lib/node_modules/broccoli-viz/lib/build-graph.js:32:3)
    at module.exports (/usr/local/Cellar/node@6/6.14.1/lib/node_modules/broccoli-viz/lib/build-graph.js:79:10)
    at Object.processNodes [as process] (/usr/local/Cellar/node@6/6.14.1/lib/node_modules/broccoli-viz/lib/process.js:5:15)
    at Object.<anonymous> (/usr/local/Cellar/node@6/6.14.1/lib/node_modules/broccoli-viz/bin/broccoli-viz:35:25)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
```

**Comment by jurecuhalev** [comment]
It turns out that I need to use 4.x release.
